name: Update README ⭐
on:
  schedule:
    - cron: "51 */4 * * *"  # Every 4 hours
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        year: [2015, 2016, 2017]
    steps:
      - uses: actions/checkout@v2
      - uses: k2bd/advent-readme-stars@v1
        with:
          userId: 1356574
          sessionCookie: ${{ secrets.AOC_SESSION }}
          year: ${{ matrix.year }}
          readmeLocation: y_${{ matrix.year }}/README.md
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README stars
